services:
  - type: web
    name: m-connect-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: CACHE_DRIVER
        value: "file"
      - key: SESSION_DRIVER
        value: "file"
      - key: QUEUE_CONNECTION
        value: "sync"